In [1]:
# memanggil pandas
import pandas as pd
# memanggil nummpy
import numpy as np
from sklearn.model_selection import train_test_split
# memanggil matplot untuk grafik
import matplotlib.pyplot as plt
# memanggil library sklearn untuk import dataset
from sklearn import datasets
# memanggil library sklearn untuk knn clasifier
from sklearn.neighbors import KNeighborsClassifier

In [4]:
# memanggil dataset 
dsetTKM = pd.read_csv('/content/data_transaksi_ok_Final.csv')
#print (dsetTKM)
# head of the data
#print(dsetTKM.head())
#print (type(dsetTKM))
#print (dsetTKM.keys())
# understanding data
print('Ukuran data : ', dsetTKM.shape)
print(pd.value_counts(dsetTKM.Fraud))
#x=dsetTKM
#y=dsetTKM
# Split dataset menjadi trainig set dan testing set
#x_train,x_test,y_train,y_test=train_test_split (x,y,test_size=0.33,random_state=0)
# printing out train and test sets
#print('X_train : ')
#print(x_train.head())
#print('')
#print('X_test : ')
#print(x_test.head())


Ukuran data :  (1000, 15)
0    605
1    395
Name: Fraud, dtype: int64


In [5]:
#Preprocessing
# Split dataset menjadi trainig set dan testing set
#x=dsetTKM
y =  dsetTKM.pop('Fraud') #pisahkan antara data dan label
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dsetTKM, y, test_size=0.33, random_state=0)


In [20]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
scaler.fit(X_train)
X_train = scaler.transform(X_train)  
X_test = scaler.transform(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [21]:
from sklearn.neighbors import KNeighborsClassifier


In [22]:
knn = KNeighborsClassifier(n_neighbors=5)


In [23]:
knn.fit(X_train, y_train)


KNeighborsClassifier()

In [24]:
y_pred = knn.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [25]:
knn.predict_proba(X_test)


array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.

In [26]:
from sklearn.metrics import classification_report, confusion_matrix


In [27]:
print(confusion_matrix(y_test, y_pred))


[[  0 202]
 [  0 128]]


In [28]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.00      0.00      0.00       202
           1       0.39      1.00      0.56       128

    accuracy                           0.39       330
   macro avg       0.19      0.50      0.28       330
weighted avg       0.15      0.39      0.22       330



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
#Membuat model Machine Learning
# Memanggil KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5,weights='uniform',algorithm='auto',metric='minkowski')
# Fitting model dengan training data and target
knn.fit (X_train,y_train)


KNeighborsClassifier()

In [31]:
#evaluasi model 

#melihat akurasi
#Accuracy Score pada Data Train
from sklearn.metrics import accuracy_score
hasil = knn.predict(X_train)  
print("Accuracy Score pada Data Train:",accuracy_score(hasil,y_train))

#Accuracy Score pada Data Testing
hasil2 = knn.predict(X_test)  
print("Accuracy Score pada Data Testing:",accuracy_score(hasil2,y_test))


Accuracy Score pada Data Train: 1.0
Accuracy Score pada Data Testing: 0.3878787878787879


In [32]:
# melakukan prediksi 
# Data yang akan diprediksi 
Data = [[1,1,3,1,1,1,1,0,3,1,1,1,1,1]] 
#Data = [[2,2,3,2,2,2,2,3,2,1,1,1,1,1]]
# melakukan prediksi berdasarkan data
Y_pred=knn.predict(Data)
print ("Hasil Prediksi Fraud:", Y_pred)

Hasil Prediksi Fraud: [1]
